- .travis.yml
- setup.py
- tox.ini
- drop Python 3.4
- add Python 3.7 and 3.8
modified:   .travis.yml
modified:   setup.py
modified:   tox.ini
> Update Python versions

- docs/basic.rst
- docs/macros.rst
- docs/migrate.rst
Just making the docs a bit better. No content was changed, just the typos and grammar.
> I fixed several typos

- docs/macros.rst
- flask_bootstrap/templates/bootstrap/table.html
- test_bootstrap_flask.py
As discussed in #70 I've added the `render_table` macro.
> Add table macro

- CHANGES.rst
- tox.ini
modified:   CHANGES.rst
modified:   tox.ini
> Fix broken `tox` environments

- CHANGES.rst
- test_bootstrap_flask.py
This fixes #78
modified:   CHANGES.rst
modified:   test_bootstrap_flask.py
> Fix `ResourceWarning: unclosed file`

- examples/app.py
- flask_bootstrap/templates/bootstrap/table.html
Integrated a form in the delete action as discussed in #77
> feat: Add form to delete action in table macro

- examples/templates/base.html
Perhaps support this via a `{{}}` macro.
> current year for copyright notice in example

- flask_bootstrap/templates/bootstrap/table.html
This remove small blue line thta shows up next to the view and edit icons when hovering mouse over them.
Question, the delete icon doens't look as it is vertivally aligned with the other two icons. Probably because it is inside a form. Any suggestions on how to fix that?
> remove unwanted hover underline next to view and edit icons

- examples/app.py
As many people start off by changing the example provided, having more variety in the example code and also an extended implementation of view, edit and delete will help people get up to speed more quickly.
> extended example with more variety

- .travis.yml
- setup.cfg
- setup.py
- tests/conftest.py
- tests/test_bootstrap.py
- tests/test_render.py
- tox.ini
> Migrate tests to pytest

- flask_bootstrap/__init__.py
> fix table macro error

- flask_bootstrap/templates/bootstrap/form.html
> Fix class for horizontal form label

- CHANGES.rst
- docs/macros.rst
- examples/templates/table.html
- flask_bootstrap/__init__.py
- flask_bootstrap/templates/bootstrap/table.html
- tests/test_render_table.py
The support to the old value will be removed in version 2.0.
fixes #135
> Change the default action_pk_placeholder to ":id"

- flask_bootstrap/__init__.py
- tests/test_bootstrap.py
> Support SRI

- docs/macros.rst
- flask_bootstrap/templates/bootstrap/table.html
> Check if CSRFProtect is enabled when using table delete action

- examples/app.py
- flask_bootstrap/__init__.py
- setup.py
- tests/test_render_table.py
- tests/test_themes.py
Improved the constructions of string and all refactored `%s` and `.format()` to use `f'{}'`. In a few places improved the length of the lines.
> conslidated string formatting

- flask_bootstrap/__init__.py
- tests/test_bootstrap.py
- tests/test_render_table.py
- Use f-string.
- Remove unnecessarily nested if statements.
- Remove repeat code definitions.
> Improve URL handling in load_js and load_css methods

- docs/macros.rst
- examples/bootstrap4/templates/icon.html
- examples/bootstrap5/templates/icon.html
- flask_bootstrap/templates/base/utils.html
- tests/test_bootstrap4/test_render_icon.py
> render_icon title and desc

- flask_bootstrap/templates/base/nav.html
Found this by validating the example with https://validator.w3.org/nu/
> removed extra quotations

- examples/bootstrap4/app.py
- examples/bootstrap4/templates/form.html
- examples/bootstrap5/app.py
- examples/bootstrap5/templates/form.html
The range sliders in Bootstrap5 need some work as can be seen in the example. The extra fields added with this commit can be used to also add more tests, increase code coverage, provide more examples.
> more field examples for more tests (bootstrap5 ranges need work)

- CHANGES.rst
- flask_bootstrap/templates/bootstrap5/form.html
> Set class form-select for SelectField

- requirements/examples.txt
> Update self version in example requirement file

- examples/bootstrap5/templates/base.html
- examples/bootstrap5/templates/nav.html
> Update nav.html to match Bootstrap5

- README.md
- docs/index.rst
Closes https://github.com/helloflask/bootstrap-flask/issues/170
> development documentation

- CHANGES.rst
- README.md
- docs/_templates/sidebarintro.html
- examples/README.rst
- examples/bootstrap5/templates/base.html
- setup.py
@greyli also upgrade these kind of URLs in CHANGES.rst?
> upgrade URLs GitHub organization

- examples/bootstrap4/templates/base.html
- examples/bootstrap4/templates/flash.html
- examples/bootstrap5/templates/base.html
- examples/bootstrap5/templates/flash.html
Closes https://github.com/helloflask/bootstrap-flask/issues/245
> Update the example for render_messages

- codecov.yml
> Disable codecov comment

- flask_bootstrap/__init__.py
fixes #331 
The integrity value added in #319 is incorrect.
> Fix incorrect JS integrity

- examples/bootstrap4/templates/icons.html
- examples/bootstrap5/templates/icons.html
- examples/update-icons.py
- flask_bootstrap/templates/bootstrap5/form.html
- tests/test_bootstrap5/test_render_form.py
See https://getbootstrap.com/docs/5.3/customize/color/ and https://getbootstrap.com/docs/5.3/migration/#utilities-2
> replaced deprecated color muted with secondary

- CHANGES.rst
- docs/macros.rst
- flask_bootstrap/templates/base/nav.html
- flask_bootstrap/templates/bootstrap4/nav.html
- flask_bootstrap/templates/bootstrap5/nav.html
- tests/test_bootstrap5/test_render_nav_item.py
and add `_badge_classes` param to the `render_nav_item` macro to set badge classes.
> Fix the badge classes in `render_nav_item` macro for Bootstrap 5
