helloflask/bootstrap-flask

docs/macros.rst
"form" was accidentally mis-spelled in the documentation, fixing it.
=> Fix typo in macros.rst

flask_bootstrap/__init__.py
Also, the ternary conditional isn't needed. The comparison already returns a bool.
=> Fix KeyError Exception if ENV isn't defined.

CHANGES.rst, docs/macros.rst, flask_bootstrap/templates/bootstrap/form.html, test_bootstrap_flask.py
I have written to macros for rendering form grids:
The first one, `render_form_row`, is in charge of rendering a row of the form, according to the desired classes.
The second one, `render_grid_form`, renders the whole form taking an iterable of calls to the first macro.
I think this is useful when one wants to customize the form but don't want to write the whole bootstrap code required.
The second macro, `render_grid_form` could be merged into render_form, but I haven't done this because for serveral reasons:
- At the moment I use them without having modified the original files, importing them from a file of my project.
- It cannot render automatically the form, because it needs to know the distribution of the fields in rows and cols, and therefore, it needs a parameter to do so.
Let me …
=> macros for rendering form grids

docs/basic.rst
Just fixing up some of the English language, and adding a missing ` ` between a `%` and `}`.
=> [trivial] Grammar fixes

CHANGES.rst, docs/advanced.rst, docs/index.rst, docs/macros.rst, examples/app.py, examples/templates/form.html, flask_bootstrap/__init__.py, flask_bootstrap/templates/bootstrap/form.html, test_bootstrap_flask.py
Add `button_size` and `button_style` for `render_field` and `render_form` macro, this will overwrite the default value set by config `BOOTSTRAP_BTN_SIZE` and `BOOTSTRAP_BTN_STYLE`.
Todo
=> Add more support for form button customization

flask_bootstrap/__init__.py
Simple update to JQuery.
Plesae don't use 3.5.0.
See: https://stackoverflow.com/questions/61177140/uncaught-typeerror-cannot-convert-object-to-primitive-valuezone-evergreen-js1/61177704#61177704
=> Update to JQuery 3.4.1 for security updates

docs/migrate.rst
Following the current migration installations fails due to a typo in the package name.
Ends in : `requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/bootstap-flask/`
=> Typo in install instructions

docs/macros.rst
Probably consolidate all the indentations of text spanning multiple lines in all rst files.
This commit should improve the formatting of https://bootstrap-flask.readthedocs.io/en/stable/macros.html#render-icon
=> improved indentation

flask_bootstrap/templates/bootstrap/form.html, tests/conftest.py, tests/test_render_field.py
=> Fix csrf token label of render field macro

CHANGES.rst, docs/macros.rst, examples/app.py, examples/templates/table.html, flask_bootstrap/static/img/new.svg, flask_bootstrap/templates/bootstrap/table.html, tests/test_render_table.py
fixes #128
Example:
```jinja2
{{ render_table(messages, show_actions=True, ..., new_url=url_for('new_message')) }}
```
The output will like this:
=> Add new_url parameter for render_table macro

CHANGES.rst, docs/macros.rst, flask_bootstrap/templates/bootstrap/table.html, tests/test_render_table.py
`custom_actions` accepts a list of tuples where a tuple should contain 3 items:
1. The button's title (what shows on hover)
2. The bootstrap icon name to render (via `render_icon` macro)
3. The `url_for()` link in the same format as the other action urls
Since the new parameter logic requires the `render_icon` macro, I've added the conditional import logic right before the table data for-loop.
**Example Usage:**
```
{{ render_table(
report_list,
titles=headers,
responsive=True,
show_actions=True,
custom_actions=[('Run', 'play-fill', url_for('run_report', report_id=':primary_key'))],
view_url=url_for('view_report', report_id=':primary_key'),
edit_url=url_for('update_report', report_id=':primary_key'),
delete_url=url_for('delete_report', report_id=':primary_key')
) }}
```
**Result:**
I'm …
=> Added custom_actions functionality to render_table macro

CHANGES.rst, docs/macros.rst, flask_bootstrap/templates/bootstrap/pagination.html, flask_bootstrap/templates/bootstrap/table.html, flask_bootstrap/templates/bootstrap/utils.html, tests/test_render_table.py
Closes #136 
Closes #145  
With the addition of the `model` parameter to the `render_table` macro we can now utilize the previously private macro `arg_url_for` (previously `_arg_url_for`) to correctly grab values from each record as it's iterated over during table rendering. This allows users to utilize the built-in [werkzeug converters](https://werkzeug.palletsprojects.com/en/2.0.x/routing/#built-in-converters) with their url parameters.
Designed with backwards compatibility in mind. Users will still be able to pass in normal `url_for` calls as well. But, anything involving placeholders would be subject to the new tuple approach.
=> Fixed compatibility with `Flask`'s built-in url type-converters

docs/macros.rst, flask_bootstrap/__init__.py, flask_bootstrap/templates/bootstrap/table.html, tests/test_render_table.py
=> Improve table action URLs handling

flask_bootstrap/templates/bootstrap/form.html
=> Fix issues in render_field macro

CHANGES.rst, docs/macros.rst, flask_bootstrap/templates/bootstrap/form.html, tests/conftest.py, tests/test_render_field.py
It supports to use `class` argument when using render_field:
```python
{{ render_field(form.username, class="myClass") }}
```
Bootstrap-Flask now combines the class you passed or the `class` value of `render_kw` with Bootstrap classes:
```html
<input class="form-control myClass" id="username" name="username"
```
This PR also fixes the issue that keyword arguments are not passed to BooleanField.
Related to #155 and #156.
=> Combine class arguments of render_field with Bootstrap classes

flask_bootstrap/templates/bootstrap/form.html, flask_bootstrap/templates/bootstrap/nav.html, flask_bootstrap/templates/bootstrap/pagination.html, flask_bootstrap/templates/bootstrap/table.html, tests/test_render_breadcrumb_item.py, tests/test_render_nav_item.py
Continues #157 
Move some whitespace in HTML attributes to if statements.
=> Remove unnecessary whitespaces generated from if statements

CHANGES.rst, docs/advanced.rst, docs/macros.rst, examples/bootstrap4/app.py, examples/bootstrap4/templates/base.html, examples/bootstrap5/app.py, flask_bootstrap/__init__.py, flask_bootstrap/templates/bootstrap4/form.html, tests/test_bootstrap4/test_render_form.py
Works for Bootstrap 4, not yet for Bootstrap 5. need help for that part.
The following one liner is probably the fix for version 5, but there is no forms.html for version 5 to add that.
<div class="form-group form-check{% if form_type == "inline" %} form-check-inline{% endif %}{% if field.type == 'SwitchField' %} form-switch{% endif %}">
=> render switch for boolean

CHANGES.rst, examples/bootstrap4/app.py, examples/bootstrap5/app.py, flask_bootstrap/templates/bootstrap4/form.html, flask_bootstrap/templates/bootstrap5/form.html, tests/test_bootstrap4/test_render_form.py, tests/test_bootstrap5/test_render_form.py
Render `DecimalRangeField` and `IntegerRangeField` for Bootstrap 4 and Bootstrap 5 correctly.
fixes #190
=> Add support for WTForms range fields

flask_bootstrap/__init__.py
The `Bootstrap` class is now a subclass of `Bootstrap4`, and provides a deprecation warning. That should prevent existing code from breaking. However, this purpose is defeated by a change in the signature of `Bootstrap.__init__()` that can break existing code. 
This change restores the previous signature.
=> Fix signature of Bootstrap.__init__() incompatible with older version.

examples/bootstrap4/templates/table.html, examples/bootstrap5/templates/table.html
The word "Customized" was mistyped to "Cutomized" in the following files:
- https://github.com/greyli/bootstrap-flask/blame/master/examples/bootstrap4/templates/table.html#L9
- https://github.com/greyli/bootstrap-flask/blame/master/examples/bootstrap5/templates/table.html#L9
I fixed the spelling.
Fixes #206
=> Fixed typos in examples

setup.py
The migration link from Flask-Bootstrap on the PyPI page is outdated.
It could be a good idea to include the whole README in the package's metadata to ensure [this page](https://pypi.org/project/Bootstrap-Flask/) is always up to date. If needed, here's how it's done in Flask: https://github.com/pallets/flask/blob/main/setup.cfg#L19.
=> Fix migration hyperlink in PyPI page

CHANGES.rst, docs/macros.rst, examples/bootstrap4/app.py, examples/bootstrap4/templates/table.html, examples/bootstrap5/app.py, examples/bootstrap5/templates/table.html, flask_bootstrap/templates/base/table.html, tests/test_bootstrap4/test_render_table.py
Please review, fixes most important part of https://github.com/greyli/bootstrap-flask/issues/118 which can be closed IMHO.
fixes #118
=> show links in table text

CHANGES.rst, docs/macros.rst, examples/bootstrap4/templates/base.html, examples/bootstrap5/templates/base.html, flask_bootstrap/templates/base/nav.html
Rename the following parameters of the `render_nav_item` macro to prevent shadowing the user's URL variables.
- badge -> _badge
- use_li -> _use_li
fixes: #215
I didn't find the way to emit a deprecate warning in a macro. So this change will release with the 2.1 version directly.
=> Rename parameters of render_nav_item

README.md
[Basic Usage](https://bootstrap-flask.readthedocs.io/en/stable/basic) url is 404
=> Fix broken URL in the README.md

examples/bootstrap4/app.py, examples/bootstrap4/templates/table.html, examples/bootstrap5/app.py, examples/bootstrap5/templates/table.html
=> Add example for using render_table without SQLAlchemy

requirements/examples.txt
Fixes #246 as 2.1.0 introduced support for `urlize_columns`-keyword to render_table MACRO.
=> Bump requirement from 2.0.2 to 2.1.0 to support urlize_columns

CHANGES.rst, docs/basic.rst, flask_bootstrap/__init__.py, flask_bootstrap/templates/base/table.html, flask_bootstrap/templates/bootstrap4/form.html, flask_bootstrap/templates/bootstrap5/form.html, tests/test_bootstrap4/test_bootstrap.py, tests/test_bootstrap5/test_bootstrap5.py
To support the usage of Boostrap-Flask together with a [strict Content Security Policy (CSP)](https://csp.withgoogle.com/docs/strict-csp.html), to have a defense in depth against XSS attacks, the following changes have been made:
1. Remove inline style declarations, use classes instead
2. Remove inline JS, use HTML + CSS instead
3. Add support of nonces with JS includes
4. Add basic usage documentation
If desired I can still add an example and/or test case for this use case.
=> Add support for strict Content Security Policy

setup.py
The links have been added in similar way https://github.com/wtforms/flask-wtf/blob/main/setup.cfg uses them. This change cannot be tested so extra care is needed when new version is published.
=> additional pypi links

CHANGES.rst, docs/macros.rst, flask_bootstrap/templates/base/table.html, tests/test_bootstrap4/test_render_table.py
This PR fixes issue #268 to allow table actions when the table data is not taken from SQLAlchemy.
Currently each action URLs is formed by looking up the row record in SQLAlchemy, using the row's primary key and the provided `model` class. Not only does this mean that the URL creation fails for records that are not taken from SQLAlchemy (or something with the same API) but it also means that there is an additional database fetch for every action on every row.
The fix here makes the `model` parameter optional, even when actions are required. If no model is provided then any fields needed for building the URL are taken from the original row data. If a model class is provided then the functionality should be identical to before, complete with the extra database queries. This allows the record …
=> Fix #268. Allow table actions when data is provided as dicts

docs/macros.rst, examples/bootstrap4/app.py, examples/bootstrap5/app.py, flask_bootstrap/__init__.py
This PR fixes the `flask.Markup` deprecation in Flask 2.3 (see upstream [changelog](https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0))
=> Address flask.Markup deprecation in Flask 2.3

flask_bootstrap/__init__.py
The existing value is for the bundle js file.
The value can be checked through the browser console when running the example application.
cc @PanderMusubi
=> Fix incorrect Bootstrap JS integrity

docs/macros.rst
Just noticed these while browsing the docs.
=> Minor typos in Macros.rst

examples/bootstrap4/app.py, examples/bootstrap4/templates/form.html, examples/bootstrap5/app.py, examples/bootstrap5/templates/form.html
Only merge this once this PR https://github.com/wtforms/wtforms/pull/755 is available in a release of WTForms
=> color field in examples

docs/macros.rst, examples/bootstrap5/templates/table.html, flask_bootstrap/templates/base/table.html, tests/test_bootstrap4/test_render_table.py
Table group dividers is available in [Bootstrap v5.2+](https://getbootstrap.com/docs/5.2/content/tables/#table-group-dividers)
Adding `body_classes` parameter to `render_table()` to be able to use that style.
* updated test 
* updated documentation
* updated bootstrap5 example app
=> Adding body_classes parameter to render_table
